/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author YenNT4
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        PromptSupport.setPrompt("Name", txtUserNameR);
        PromptSupport.setPrompt("PassWord", pwdUserR);
        PromptSupport.setPrompt("First Name", txtFirstName);
        PromptSupport.setPrompt("Last Name", txtLastName);
        PromptSupport.setPrompt("Your Email", txtEmail);
        PromptSupport.setPrompt("Repeat Email", txtRepeatEmail);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtuserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdUser = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtUserNameR = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRepeatEmail = new javax.swing.JTextField();
        pwdUserR = new javax.swing.JPasswordField();
        txtLastName = new javax.swing.JTextField();
        cbbSex = new javax.swing.JComboBox();
        btnRegistry = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblReEmail = new javax.swing.JLabel();
        lblBackgroundCarry = new javax.swing.JLabel();

        Login.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName :");
        Login.add(jLabel2);
        jLabel2.setBounds(100, 140, 90, 17);
        Login.add(txtuserName);
        txtuserName.setBounds(100, 170, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        Login.add(jLabel3);
        jLabel3.setBounds(100, 220, 130, 30);
        Login.add(pwdUser);
        pwdUser.setBounds(100, 260, 240, 30);

        btnLogin.setBackground(new java.awt.Color(0, 204, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(153, 0, 204));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        Login.add(btnLogin);
        btnLogin.setBounds(250, 320, 90, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 255, 255)), "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        txtUserNameR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameRFocusLost(evt);
            }
        });

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtRepeatEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepeatEmailFocusLost(evt);
            }
        });

        pwdUserR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdUserRActionPerformed(evt);
            }
        });
        pwdUserR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdUserRFocusLost(evt);
            }
        });

        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });

        cbbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", "Unknown" }));

        btnRegistry.setText("Registry");
        btnRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistryActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserNameR)
                    .addComponent(txtEmail)
                    .addComponent(txtRepeatEmail)
                    .addComponent(pwdUserR)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cbbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtUserNameR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pwdUserR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepeatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Login.add(jPanel2);
        jPanel2.setBounds(480, 110, 320, 380);

        lblBackgroundCarry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skype-login.png"))); // NOI18N
        lblBackgroundCarry.setText("avsdfasdf");
        Login.add(lblBackgroundCarry);
        lblBackgroundCarry.setBounds(0, 0, 830, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        MainFrame mfraim = (MainFrame) SwingUtilities.getRoot(this);
        mfraim.showHomePage();


    }//GEN-LAST:event_btnLoginActionPerformed

    private void pwdUserRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdUserRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdUserRActionPerformed

    private void btnRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistryActionPerformed
        String userName = txtUserNameR.getText();
        String pw = pwdUserR.getSelectedText();
        String fName = txtFirstName.getText();
        String lName = txtLastName.getText();
        String email = txtEmail.getText();
        String reEmail = txtRepeatEmail.getText();


    }//GEN-LAST:event_btnRegistryActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtUserNameR.setText("");
        pwdUserR.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtRepeatEmail.setText("");
        cbbSex.setSelectedIndex(0);
        lblUserName.setText("");
        lblPassword.setText("");
        lblEmail.setText("");
        lblReEmail.setText("");
        lblName.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtUserNameRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameRFocusLost
        validateUserNameField();
    }//GEN-LAST:event_txtUserNameRFocusLost

    private void pwdUserRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdUserRFocusLost
        validatePasswordField();
    }//GEN-LAST:event_pwdUserRFocusLost

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        validateNamesField();
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        validateNamesField();
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        validateEmailField();
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtRepeatEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepeatEmailFocusLost
        validateReEmailField();
    }//GEN-LAST:event_txtRepeatEmailFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistry;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbbSex;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackgroundCarry;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReEmail;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pwdUser;
    private javax.swing.JPasswordField pwdUserR;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtRepeatEmail;
    private javax.swing.JTextField txtUserNameR;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables

    private void validateUserNameField() {
        if (ValidateData.validateUserName(txtUserNameR.getText())) {
            lblUserName.setForeground(Color.green);
            lblUserName.setText("Validated");

        } else {
            lblUserName.setForeground(Color.red);
            lblUserName.setText("Your name containts characters that are not allowed");
        }
    }

    private void validatePasswordField() {
        if (ValidateData.validatePassword(pwdUserR.getPassword())) {
            lblPassword.setForeground(Color.green);
            lblPassword.setText("Validated");
        } else {
            lblPassword.setForeground(Color.red);
            lblPassword.setText("6-characters minimum");
        }
    }

    private void validateNamesField() {
        if ((ValidateData.validateName(txtFirstName.getText())) && (ValidateData.validateName(txtLastName.getText()))) {
            lblName.setForeground(Color.GREEN);
            lblName.setText("Validated");
        } else {
            lblName.setForeground(Color.red);
            lblName.setText("You must be enter full name");
        }
    }

    private void validateEmailField() {
        if (ValidateData.validateEmail(txtEmail.getText())) {
            lblEmail.setForeground(Color.GREEN);
            lblEmail.setText("Validated");
        } else {
            lblEmail.setForeground(Color.red);
            lblEmail.setText("Email not validate");
        }
    }

    private void validateReEmailField() {
        if (!txtRepeatEmail.getText().equals(txtEmail.getText())) {
            lblReEmail.setForeground(Color.red);
            lblReEmail.setText("Email not match");
        } else {
            if (ValidateData.validateEmail(txtEmail.getText())) {
                lblReEmail.setForeground(Color.GREEN);
                lblReEmail.setText("Validated");
            } else {
                lblReEmail.setForeground(Color.red);
                lblReEmail.setText("Email not validate");
            }
        }
    }
}
